### ISSUE TITLE
Link to deleted video in Second Estrogenic Puberty 101

### ISSUE THREAD

**Issue by BujjuIsDumb** [GenderDysphoria/GenderDysphoria.fyi#89] opened 2022-03-28 00:16 UTC
The video for "hip rotation" in the Anterior Pelvic Tilt section of Second Estrogenic Puberty 101 is gone because the account was terminated.

**Comment by izzergh** [comment] 2022-05-04 00:58
Looks like a duplicate of #42

**Comment by BujjuIsDumb** [comment] 2022-05-04 01:00
No #42 is a duplicate of this, check the dates

**Comment by BujjuIsDumb** [comment] 2022-05-04 01:00
> Looks like a duplicate of #42

No #42 is a duplicate of this, check the dates

**Comment by Twipped** [comment] 2022-05-04 03:03
Issue numbers increment upwards, so by definition #42 would have to predate this issue (#89).

This is indeed a duplicate, you didn't look at the year.

**Closed** 2022-05-04 03:03 UTC
